#Please note that we are using lua 5.1
FIND_PATH(PYTHON_INCLUDE_DIR python.h)

IF (NOT PYTHON_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "Cannot find PYTHON headers!")
ENDIF (NOT PYTHON_INCLUDE_DIR)

FIND_LIBRARY(PYTHON_LIBRARY NAMES python)

IF (NOT PYTHON_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find PYTHON libraries!")
ENDIF (NOT PYTHON_LIBRARY)

IF (NOT Python_FIND_QUIETLY)
  MESSAGE(STATUS "Found Python: ${PYTHON_LIBRARY}")
ENDIF (NOT Python_FIND_QUIETLY)

FIND_LIBRARY(UTIL_LIBRARY NAMES util)

IF (NOT UTIL_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find Util libraries!")
ENDIF (NOT UTIL_LIBRARY)