#Please note that we are using lua 5.1
FIND_PATH(LUA_INCLUDE_DIR lua.h)

IF (NOT LUA_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "Cannot find LUA headers!")
ENDIF (NOT LUA_INCLUDE_DIR)

FIND_LIBRARY(LUA_LIBRARY NAMES lua)

IF (NOT LUA_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find LUA libraries!")
ENDIF (NOT LUA_LIBRARY)

IF (NOT Lua_FIND_QUIETLY)
  MESSAGE(STATUS "Found Lua: ${LUA_LIBRARY}")
ENDIF (NOT Lua_FIND_QUIETLY)

